# Dockerfile.backend - Backend only
FROM node:18-alpine

WORKDIR /app
COPY backend/package*.json ./
RUN npm install
COPY backend .

ENV NODE_ENV=production
ENV MONGO_URI=mongodb+srv://Admin:Admin786@cluster0.krbh692.mongodb.net/vcommerce?retryWrites=true&w=majority
ENV PORT=3000

EXPOSE 3000
CMD ["node", "src/index.js"]